#!/bin/bash
# Bionic (Steel) conky wrapper - modern procedural rewrite
DIR="$HOME/.conky/bionic"
CFG="$DIR/config/bionicrc"
LOG="$DIR/bionic.log"

start() {
  setsid conky -d -c "$CFG" </dev/null >"$LOG" 2>&1 &
}

stop() {
  pkill -f "[c]onky .*bionicrc"
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)   start ;;
  stop)    stop ;;
  restart) restart ;;
  *) echo "usage: $0 {start|stop|restart}"; exit 1 ;;
esac