[general]
bars = 12
sensitivity = 200
autosens = 0
noise_reduction = 0.5

[input]
method = pulse
source = auto

[output]
method = raw
raw_target = /tmp/cava_fifo
data_format = ascii
ascii_max_range = 8
bar_delimiter = 59
